require("plugins")
require("base")
require("keymaps")
require("plugin-config.nvim-tree")
require("plugin-config.colorscheme")
require("plugin-config.comment")
require("plugin-config.lualine")
require("plugin-config.autopairs")
require("plugin-config.telescope")
require("plugin-config.nvim-cmp")
require("plugin-config.lsp.mason")
require("plugin-config.lsp.lspconfig")
require("plugin-config.lsp.lspsaga")
vim.api.nvim_command('highlight NvimTreeIndentMarker guifg=#3f5cff')
